service: product-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true

plugins:
  - serverless-offline

functions:
  get-products:
    handler: handler.getProductsList
    events:
      - http:
          path: products
          method: GET
  get-product:
    handler: handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: GET
