service: product-service

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline

functions:
  get-products:
    handler: handler.getProductsList
    events:
      - http:
          path: products
          method: GET
  get-product:
    handler: handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: GET


