service: import-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    BUCKET: import-service-mjrodriguezm21
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
          Resource: "arn:aws:s3:::import-service-mjrodriguezm21/*"
functions:
  importProductsFile:
    handler: importProductsFiles/handler.importProductsFile
    events:
      - http:
          path: import
          method: GET
          request:
            parameters:
              querystrings:
                name: true

resources:
  Resources:
    S3Bucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: import-service-mjrodriguezm21
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
    S3BucketPolicy:
      Type: "AWS::S3::BucketPolicy"
      Properties:
        Bucket:
          Ref: "S3Bucket"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: "s3:GetObject"
              Resource:
                Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - Ref: "S3Bucket"
                    - "/*"
